# Generated by Django 5.1.1 on 2024-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_machine_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
