# Generated by Django 5.1.1 on 2024-10-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_machine_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcode',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='error-files'),
        ),
        migrations.AddField(
            model_name='errorcode',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='errpr-pictures'),
        ),
    ]
