# Generated by Django 5.1.1 on 2024-11-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0008_errorprotocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorprotocol',
            options={'verbose_name': 'Error'},
        ),
        migrations.AddField(
            model_name='errorprotocol',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoApp.machine'),
        ),
    ]
