# Generated by Django 5.1.1 on 2024-11-15 11:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0010_alter_errorprotocol_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorcode',
            name='files',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='errorcode',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
