# Generated by Django 5.1.1 on 2024-12-04 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0011_alter_errorcode_files_alter_errorcode_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorcode',
            options={'ordering': ['error_code'], 'verbose_name': 'ErrorCode', 'verbose_name_plural': 'ErrorCodes'},
        ),
        migrations.AlterModelOptions(
            name='errorprotocol',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Error'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name'], 'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AddField(
            model_name='errorprotocol',
            name='category',
            field=models.CharField(blank=True, choices=[('Fehler', 'Fehler'), ('Störung', 'Störung'), ('Ausfall', 'Ausfall'), ('Schaden', 'Schaden')], default='Fehler', max_length=15),
        ),
        migrations.AlterField(
            model_name='errorprotocol',
            name='error_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_protocols', to='djangoApp.errorcode'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.CharField(db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='notes',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
