# Generated by Django 5.1.1 on 2024-10-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=20)),
                ('error_description', models.CharField(max_length=400)),
                ('solution', models.CharField(max_length=400)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.machine')),
            ],
            options={
                'verbose_name': 'ErrorCode',
                'verbose_name_plural': 'ErrorCodes',
            },
        ),
    ]
