# Generated by Django 5.1.1 on 2024-10-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_errorcode_files_errorcode_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorcode',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='error-pictures'),
        ),
    ]
