# Generated by Django 5.1.1 on 2024-10-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0006_alter_errorcode_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_image'),
        ),
    ]
