# Generated by Django 5.1.1 on 2024-11-07 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0007_machine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('error_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_protocols', to='djangoApp.errorcode')),
            ],
        ),
    ]
