# Generated by Django 5.1.1 on 2024-11-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0009_alter_errorprotocol_options_errorprotocol_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorprotocol',
            name='error_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_protocols', to='djangoApp.errorcode'),
        ),
    ]
